In [2]:
# I love python
# python is good
# python is useful.

In [3]:
# unique words
# I love python is good useful
# [111000]
# [001110]
# [001101]
# Machine can read or translate the sentences or texts

In [4]:
# N-gram techniques
# (1,2)------> I love python is good useful .
# ilove lovepython python is good isuseful .
# [111000]
# [001110]
# [001101]
# [11000]
# [00110]
# [00101]

# Text Representation

In [5]:
# 1. Bag of words
# We use countvectorization

In [6]:
import numpy as np
import pandas as pd

In [9]:
df = pd.DataFrame({'text':['people watch cricket', 'player was player',
                   'people write comment',
                   'cricket play comment'], 'output':[1,1,0,0]})

In [10]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv = CountVectorizer()

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [16]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [17]:
# 2. N-grams

In [18]:
# cv = CountVectorizer(ngram_range(2,2))

In [19]:
v = CountVectorizer(ngram_range=(1,2))
# v = CountVectorizer(ngram_range=(2,2))

In [20]:
bow = v.fit_transform(df['text'])

In [21]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [22]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [ ]:
# TF(term frequency)
# 2. idf(inverse document frequency)

In [24]:
# TF(t,d) = (Number of accurences of term t in document d)/(Total number of term in the document d)
# example ==>
# d1 = people watch cricket.

# tf(people,d1)=1/3

# d2 = match was match
# tf(match,d2)=2/3

In [25]:
# IDF(t) = Loge (Total number of documents in the corpus)/(Number of documents with term t in them)
# here corpus means number of sentences

# Example ==>
# d1 = people watch cricket
# d2 = cricket was cricket
# d3 = people write comment
# d4 = cricket write comment

# idf(cricket) = log(4/4)
# idf (people) = Log(4/2)

In [26]:
# we can use this by apply feature_extraction method in sklearn

In [27]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [29]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']


In [ ]:
# ner in nlp
# Googletrans library for hinglish